# Generated by Django 4.2.13 on 2024-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_FName', models.CharField(max_length=50)),
                ('P_MName', models.CharField(blank=True, max_length=50, null=True)),
                ('P_LName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Person_Type', models.CharField(max_length=50)),
            ],
        ),
    ]
