# Generated by Django 5.0.6 on 2024-06-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activity_staff_staffactivityassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.child')),
            ],
        ),
    ]
