# Generated by Django 5.0.6 on 2024-06-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_otherexpenses_expense_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='other_expense',
        ),
    ]
