# Generated by Django 5.0.6 on 2024-06-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_expense_other_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='average_cost',
        ),
    ]
