# Generated by Django 5.0.6 on 2024-06-13 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_child_age_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpenses',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
