# Generated by Django 5.0.6 on 2024-06-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_otherexpenses_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cost',
        ),
        migrations.AlterField(
            model_name='otherexpenses',
            name='date',
            field=models.DateField(),
        ),
    ]
