# Generated by Django 5.0.6 on 2024-06-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_activity_cost_alter_otherexpenses_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='age',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
    ]
