# Generated by Django 5.0.6 on 2024-06-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_parent_age_remove_staff_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherexpenses',
            old_name='cost',
            new_name='amount',
        ),
    ]
